Add script name to error-exit output.

diff --git a/scripts/lib/func/exit-error b/scripts/lib/func/exit-error
--- a/scripts/lib/func/exit-error
+++ b/scripts/lib/func/exit-error
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 function exit-error {
-	echo "Error: $1" >&2
+	local script_name="$(basename "$0")"
+	echo "Error: $script_name: $1" >&2
 	exit ${2:-1}
 }
